version: '2'
services:
    hospitalmanagementsystem-app:
        image: hospitalmanagementsystem
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hospitalmanagementsystem-mysql:3306/hospitalmanagementsystem?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hospitalmanagementsystem-mysql:
        extends:
            file: mysql.yml
            service: hospitalmanagementsystem-mysql
